<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<section class="page-landing">
    <img class="logo" src="<?php echo $this->basePath() ?>/pub/images/emthemes-logo.png" alt="Magento"/>
    <p class="text-version">
        <?php echo 'Compability with Magento Version' . ' ' . $this->version; ?>
    </p>
    <p class="text-welcome">
       Welcome to Emthemes Magento 2.0 theme Installation.
        <br>
        Click 'Agree and Set Up our Themes' 
		<!--
		or read <a href="http://devdocs.magento.com/guides/v1.0/install-gde/install/install-web.html" target="_blank">Getting Started</a> to learn more.
		-->
    </p>
    <p class="text-terms">
        <a href="" ng-click="previousState()">Terms & Agreement</a>
    </p>
    <button
        type="button"
        class="btn btn-large btn-prime btn-submit"
        ng-click="nextState()"
        >Agree and Installation Emthemes 2.0</button>
</section>
